apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\KomposeTool\kompose.exe convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.4.0 (c7964e7)
  labels:
    io.kompose.service: daprsub
  name: daprsub
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: daprsub
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: daprsub
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "daprsub"
        dapr.io/app-port: "80"
    spec:
      containers:
      - image: venkateshsrini3/daprsub
        name: daprsub
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
