apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: rabbitmqbus
  namespace: default
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: host
    value: "amqp://user:XXXXXX@rabbitmq:5672/"
  - name: durable
    value: "false"
  - name: deletedWhenUnused
    value: "false"
  - name: autoAck
    value: "false"
  - name: concurrencyMode
    value: parallel